version: '3'

services:
  backend:
    image: husnain239/todo-backend:latest
    ports:
      - "50010:50010"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo
      - PORT=50010
    depends_on:
      - mongo
    restart: always

  frontend:
    image: husnain239/todo-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: 