apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ${DOCKER_USERNAME}/todo-backend:latest
        ports:
        - containerPort: 50010
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/todo"
        - name: PORT
          value: "50010"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 50010
    targetPort: 50010
  type: ClusterIP 