name: Build and Push Docker Images

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Directory Structure
        run: |
          echo "Workspace directory:"
          ls -la
          echo "Frontend directory:"
          ls -la frontend/
          echo "Frontend public directory:"
          ls -la frontend/public/ || echo "Public directory not found!"

      - name: Check Docker Hub Credentials
        run: |
          echo "Using username: ${{ secrets.DOCKER_USERNAME }}"
          echo "Password provided: ${{ secrets.DOCKER_PASSWORD != '' }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-backend:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/todo-frontend:latest
          platforms: linux/amd64,linux/arm64

      - name: Notify on success
        if: success()
        run: echo "Successfully built and pushed Docker images to Docker Hub" 